name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Extract tag version number
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Update module.json (version + URLs)
        uses: restackio/update-json-file-action@2.1
        with:
          file: module.json
          fields: "{'version':'${{ steps.get_version.outputs.version-without-v }}', 'url':'https://github.com/${{ github.repository }}', 'manifest':'https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.json', 'download':'https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.zip'}"

      - name: Create module.zip
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: module.zip
          path: |
            module.json
            module/src
            module/languages

      - name: Update Release with Files
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./module.json,./module.zip"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
